// One-off / re-runnable Pexels scraper.
//   - product cover images  → /tmp/operator-covers.sql  (apply with wrangler d1)
//   - top NZ destinations   → src/app/explore/spots-data.ts
//
// Run:  PEXELS_KEY=<key> node scripts/scrape-pexels.mjs
//
// Pexels free tier = 200 req/hour; this makes ~21 requests with a small delay.
import { writeFileSync } from "node:fs";

const KEY = process.env.PEXELS_KEY;
if (!KEY) {
  console.error("PEXELS_KEY env var missing");
  process.exit(1);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const esc = (s) => String(s).replace(/'/g, "''");

async function search(query) {
  const url =
    `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}` +
    `&per_page=1&orientation=landscape&size=large`;
  const r = await fetch(url, { headers: { Authorization: KEY } });
  if (!r.ok) {
    console.error("  pexels", r.status, "for", query);
    return null;
  }
  const d = await r.json();
  return d.photos?.[0] ?? null;
}

// slug → search query tuned to each product's location / activity
const OPERATORS = {
  "canopy-tours": "Rotorua native forest canopy New Zealand",
  kjet: "Queenstown jet boat river New Zealand",
  nzski: "Coronet Peak ski snow mountain New Zealand",
  "skycity-adelaide": "Adelaide city skyline Australia night",
  "skycity-auckland": "Auckland Sky Tower skyline New Zealand",
  "skycity-hamilton": "Hamilton Waikato river New Zealand",
  "skycity-hotels": "luxury hotel suite interior",
  "skycity-queenstown": "Queenstown waterfront lake Wakatipu New Zealand",
  "southern-discoveries": "Milford Sound fiord cruise New Zealand",
  hermitage: "Aoraki Mount Cook alpine New Zealand",
  "ultimate-hikes": "Fiordland Milford Track hiking New Zealand",
};

const SPOTS = [
  { key: "milford", en: "Milford Sound", zh: "米尔福德峡湾", regionEn: "Fiordland", regionZh: "峡湾国家公园", q: "Milford Sound New Zealand" },
  { key: "queenstown", en: "Queenstown", zh: "皇后镇", regionEn: "Otago", regionZh: "奥塔哥", q: "Queenstown New Zealand aerial lake" },
  { key: "hobbiton", en: "Hobbiton", zh: "霍比特村", regionEn: "Waikato", regionZh: "怀卡托", q: "Hobbiton movie set New Zealand" },
  { key: "rotorua", en: "Rotorua", zh: "罗托鲁瓦", regionEn: "Bay of Plenty", regionZh: "丰盛湾", q: "Rotorua geothermal hot spring New Zealand" },
  { key: "tongariro", en: "Tongariro", zh: "汤加里罗", regionEn: "Central Plateau", regionZh: "中央高原", q: "Tongariro Alpine Crossing New Zealand" },
  { key: "aoraki", en: "Aoraki / Mt Cook", zh: "库克山", regionEn: "Canterbury", regionZh: "坎特伯雷", q: "Aoraki Mount Cook New Zealand" },
  { key: "bayofislands", en: "Bay of Islands", zh: "岛屿湾", regionEn: "Northland", regionZh: "北地", q: "Bay of Islands New Zealand" },
  { key: "franzjosef", en: "Franz Josef Glacier", zh: "弗朗茨·约瑟夫冰川", regionEn: "West Coast", regionZh: "西海岸", q: "Franz Josef Glacier New Zealand" },
  { key: "tekapo", en: "Lake Tekapo", zh: "特卡波湖", regionEn: "Mackenzie", regionZh: "麦肯齐", q: "Lake Tekapo New Zealand night stars" },
  { key: "waitomo", en: "Waitomo Caves", zh: "怀托摩洞穴", regionEn: "Waikato", regionZh: "怀卡托", q: "Waitomo glowworm caves New Zealand" },
];

// ---- products ----
let sql = "";
for (const [slug, q] of Object.entries(OPERATORS)) {
  const p = await search(q);
  await sleep(350);
  if (!p) {
    console.error("op", slug, "✗ (no photo)");
    continue;
  }
  const credit = JSON.stringify({ by: p.photographer, url: p.url });
  sql += `UPDATE operators SET cover_image_url='${esc(p.src.large2x)}', cover_image_credit='${esc(credit)}' WHERE slug='${slug}';\n`;
  console.error("op", slug, "✓", p.photographer);
}
writeFileSync("/tmp/operator-covers.sql", sql);
console.error("wrote /tmp/operator-covers.sql");

// ---- destination spots ----
const spots = [];
for (const s of SPOTS) {
  const p = await search(s.q);
  await sleep(350);
  spots.push({
    key: s.key,
    en: s.en,
    zh: s.zh,
    regionEn: s.regionEn,
    regionZh: s.regionZh,
    img: p?.src?.large2x ?? "",
    by: p?.photographer ?? "",
    creditUrl: p?.url ?? "",
  });
  console.error("spot", s.key, p ? "✓" : "✗");
}

const ts = `// AUTO-GENERATED by scripts/scrape-pexels.mjs — top NZ destinations + Pexels
// imagery. Re-run: PEXELS_KEY=<key> node scripts/scrape-pexels.mjs
// Imagery hotlinked from Pexels (free, attribution shown on /explore).

export interface Spot {
  key: string;
  en: string;
  zh: string;
  regionEn: string;
  regionZh: string;
  img: string;
  by: string;
  creditUrl: string;
}

export const SPOTS: Spot[] = ${JSON.stringify(spots, null, 2)};
`;
writeFileSync("src/app/explore/spots-data.ts", ts);
console.error("wrote src/app/explore/spots-data.ts");
console.error("done");
