#!/usr/bin/env python3
"""
Compile seed/operators/<slug>/courses.json -> infra/seed.sql

Why Python (not TypeScript): seed compilation is offline-only, runs once per
content change, and Python's escape rules for SQLite strings are simpler.
The output SQL is then applied via:

    cd web && npx wrangler d1 execute tourtrain-db --remote --file=../infra/seed.sql
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS_DIR = ROOT / "seed" / "operators"
OUT = ROOT / "infra" / "seed.sql"


def q(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def collect() -> str:
    lines: list[str] = []
    lines.append("-- AUTO-GENERATED by seed/scripts/build_seed_sql.py — do not edit by hand")
    lines.append("-- (D1 wraps each --file execution in a transaction automatically;")
    lines.append("--  do NOT use BEGIN TRANSACTION / COMMIT here.)")
    lines.append("")

    for op_dir in sorted(OPS_DIR.iterdir()):
        cfile = op_dir / "courses.json"
        if not cfile.exists():
            continue
        data = json.loads(cfile.read_text())
        op = data["operator"]

        lines.append(f"-- ===== operator: {op['slug']} =====")
        lines.append(
            "INSERT OR REPLACE INTO operators "
            "(id, slug, name, display_name, country, primary_lang, cover_color, contact_email, status) VALUES "
            f"({q(op['id'])}, {q(op['slug'])}, {q(op['name'])}, {q(op.get('display_name'))}, "
            f"{q(op.get('country', 'NZ'))}, {q(op.get('primary_lang', 'en'))}, "
            f"{q(op.get('cover_color'))}, {q(op.get('contact_email'))}, {q(op.get('status', 'active'))});"
        )
        lines.append("")

        for course in data.get("courses", []):
            lines.append(
                "INSERT OR REPLACE INTO courses "
                "(id, operator_id, slug, title, summary, cover_color, emoji, primary_lang, status, est_minutes) VALUES "
                f"({q(course['id'])}, {q(op['id'])}, {q(course['slug'])}, "
                f"{q(course['title'])}, {q(course.get('summary'))}, "
                f"{q(course.get('cover_color'))}, {q(course.get('emoji'))}, "
                f"{q(course.get('primary_lang', 'en'))}, {q(course.get('status', 'draft'))}, "
                f"{q(course.get('est_minutes'))});"
            )

            for module in course.get("modules", []):
                lines.append(
                    "INSERT OR REPLACE INTO modules "
                    "(id, course_id, slug, title, summary, est_minutes, position) VALUES "
                    f"({q(module['id'])}, {q(course['id'])}, {q(module['slug'])}, "
                    f"{q(module['title'])}, {q(module.get('summary'))}, "
                    f"{q(module.get('est_minutes'))}, {q(module.get('position', 0))});"
                )

                for idx, block in enumerate(module.get("blocks", [])):
                    block_id = f"b_{module['id']}_{idx:03d}"
                    lines.append(
                        "INSERT OR REPLACE INTO content_blocks "
                        "(id, module_id, position, kind, text_md, image_r2_key, video_uid, pdf_r2_key, caption, lang) VALUES "
                        f"({q(block_id)}, {q(module['id'])}, {idx}, {q(block['kind'])}, "
                        f"{q(block.get('text_md'))}, {q(block.get('image_r2_key'))}, "
                        f"{q(block.get('video_uid'))}, {q(block.get('pdf_r2_key'))}, "
                        f"{q(block.get('caption'))}, {q(block.get('lang', 'en'))});"
                    )
            lines.append("")

        # Demo Q&A logs (so the operator dashboard has something to show on Day 9)
        for i, qa in enumerate(data.get("demo_qa_log", [])):
            qa_id = f"qa_{op['slug']}_{i:03d}"
            # We "replay" each demo question N times so asks count is realistic.
            asks = int(qa.get("asks", 1))
            for j in range(min(asks, 50)):  # cap at 50 inserts per Q to keep file small
                row_id = f"{qa_id}_{j:02d}"
                lines.append(
                    "INSERT OR REPLACE INTO qa_logs "
                    "(id, operator_id, question, question_lang, answer, answer_lang, source_kind) VALUES "
                    f"({q(row_id)}, {q(op['id'])}, {q(qa['q'])}, {q(qa.get('lang', 'en'))}, "
                    f"{q('(seeded answer placeholder)')}, {q(qa.get('lang', 'en'))}, "
                    f"{q(qa.get('source', 'rag'))});"
                )
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    sql = collect()
    OUT.write_text(sql)
    print(f"wrote {OUT}  ({len(sql.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
