#!/usr/bin/env python3
"""
Compile seed/operators/<slug>/courses.json -> infra/seed.sql.

Output uses ONE batched INSERT per table (multiple VALUES tuples), because
`wrangler d1 execute --local` rejects files with many separate INSERT statements
("several transactions" heuristic). The remote `--remote` mode accepts either,
so this format works for both.

Apply with:
    cd web && npx wrangler d1 execute tourtrain-db --local  --file=../infra/seed.sql
    cd web && npx wrangler d1 execute tourtrain-db --remote --file=../infra/seed.sql
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS_DIR = ROOT / "seed" / "operators"
OUT = ROOT / "infra" / "seed.sql"


def q(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def batched_insert(table: str, columns: list[str], rows: list[tuple]) -> str:
    if not rows:
        return ""
    cols_sql = ", ".join(columns)
    values_sql = ",\n  ".join(
        "(" + ", ".join(q(v) for v in row) + ")" for row in rows
    )
    return f"INSERT OR REPLACE INTO {table} ({cols_sql}) VALUES\n  {values_sql};\n"


def collect() -> str:
    operators_rows: list[tuple] = []
    courses_rows: list[tuple] = []
    modules_rows: list[tuple] = []
    blocks_rows: list[tuple] = []
    qa_rows: list[tuple] = []

    for op_dir in sorted(OPS_DIR.iterdir()):
        cfile = op_dir / "courses.json"
        if not cfile.exists():
            continue
        data = json.loads(cfile.read_text())
        op = data["operator"]

        operators_rows.append(
            (
                op["id"],
                op["slug"],
                op["name"],
                op.get("display_name"),
                op.get("country", "NZ"),
                op.get("primary_lang", "en"),
                op.get("cover_color"),
                op.get("contact_email"),
                op.get("status", "active"),
            )
        )

        for course in data.get("courses", []):
            ai_examples = course.get("ai_examples")
            ai_examples_json = json.dumps(ai_examples, ensure_ascii=False) if ai_examples else None
            courses_rows.append(
                (
                    course["id"],
                    op["id"],
                    course["slug"],
                    course["title"],
                    course.get("summary"),
                    course.get("cover_color"),
                    course.get("emoji"),
                    course.get("primary_lang", "en"),
                    course.get("status", "draft"),
                    course.get("est_minutes"),
                    ai_examples_json,
                )
            )

            for module in course.get("modules", []):
                modules_rows.append(
                    (
                        module["id"],
                        course["id"],
                        module["slug"],
                        module["title"],
                        module.get("summary"),
                        module.get("est_minutes"),
                        module.get("position", 0),
                    )
                )

                for idx, block in enumerate(module.get("blocks", [])):
                    block_id = f"b_{module['id']}_{idx:03d}"
                    blocks_rows.append(
                        (
                            block_id,
                            module["id"],
                            idx,
                            block["kind"],
                            block.get("text_md"),
                            block.get("image_r2_key"),
                            block.get("video_uid"),
                            block.get("pdf_r2_key"),
                            block.get("caption"),
                            block.get("lang", "en"),
                        )
                    )

        for i, qa in enumerate(data.get("demo_qa_log", [])):
            qa_id = f"qa_{op['slug']}_{i:03d}"
            asks = int(qa.get("asks", 1))
            for j in range(min(asks, 50)):
                row_id = f"{qa_id}_{j:02d}"
                qa_rows.append(
                    (
                        row_id,
                        op["id"],
                        qa["q"],
                        qa.get("lang", "en"),
                        "(seeded answer placeholder)",
                        qa.get("lang", "en"),
                        qa.get("source", "rag"),
                    )
                )

    parts = [
        "-- AUTO-GENERATED by seed/scripts/build_seed_sql.py — do not edit by hand",
        "-- Format: ONE batched INSERT per table (wrangler --local needs this).",
        "",
        batched_insert(
            "operators",
            ["id", "slug", "name", "display_name", "country", "primary_lang",
             "cover_color", "contact_email", "status"],
            operators_rows,
        ),
        batched_insert(
            "courses",
            ["id", "operator_id", "slug", "title", "summary", "cover_color",
             "emoji", "primary_lang", "status", "est_minutes", "ai_examples_json"],
            courses_rows,
        ),
        batched_insert(
            "modules",
            ["id", "course_id", "slug", "title", "summary", "est_minutes", "position"],
            modules_rows,
        ),
        batched_insert(
            "content_blocks",
            ["id", "module_id", "position", "kind", "text_md", "image_r2_key",
             "video_uid", "pdf_r2_key", "caption", "lang"],
            blocks_rows,
        ),
        batched_insert(
            "qa_logs",
            ["id", "operator_id", "question", "question_lang", "answer",
             "answer_lang", "source_kind"],
            qa_rows,
        ),
    ]
    return "\n".join(parts) + "\n"


def main() -> int:
    sql = collect()
    OUT.write_text(sql)
    print(f"wrote {OUT}  ({len(sql.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
