import { TopBar } from "../_components/top-bar";
import { getLocale, t } from "@/lib/i18n";
import { SPOTS } from "./spots-data";

export const dynamic = "force-dynamic";

/**
 * /explore — a visual showcase of New Zealand's headline destinations in an
 * irregular photo mosaic (à la newzealand.com). No AI bar, no product list —
 * this surface is reserved for big imagery (and, in future, VIP suppliers'
 * photo / video features). Imagery is sourced from Pexels (see spots-data.ts,
 * regenerated by scripts/scrape-pexels.mjs).
 */

// Asymmetric span pattern for the desktop 4-col grid (auto-flow dense fills the
// gaps). Mobile collapses to a simple 2-col grid via the base classes.
const SPANS = [
  "md:col-span-2 md:row-span-2",
  "md:col-span-1 md:row-span-1",
  "md:col-span-1 md:row-span-1",
  "md:col-span-1 md:row-span-2",
  "md:col-span-1 md:row-span-1",
  "md:col-span-2 md:row-span-1",
  "md:col-span-1 md:row-span-1",
  "md:col-span-1 md:row-span-2",
  "md:col-span-2 md:row-span-1",
  "md:col-span-1 md:row-span-1",
];

export default async function ExplorePage() {
  const [locale, tr] = await Promise.all([getLocale(), t()]);
  const zh = locale === "zh-CN";

  return (
    <div className="min-h-screen bg-white text-slate-900 font-sans antialiased text-[16px]">
      <TopBar />

      <section className="relative overflow-hidden">
        <div
          aria-hidden
          className="absolute inset-0 -z-0"
          style={{
            background:
              "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(16,185,129,0.08) 0%, transparent 60%)",
          }}
        />
        <div className="relative px-5 sm:px-8 pt-14 sm:pt-20 pb-8 max-w-6xl mx-auto">
          <div className="text-[11px] tracking-widest font-mono text-emerald-700/70 mb-2">
            {tr.ex_label}
          </div>
          <h1 className="text-[34px] sm:text-[48px] leading-[1.05] font-semibold tracking-tight text-slate-900">
            {tr.ex_title}
          </h1>
          <p className="mt-3 text-[15px] sm:text-[18px] text-slate-600 max-w-2xl leading-relaxed">
            {tr.ex_subtitle}
          </p>
        </div>
      </section>

      <section className="px-5 sm:px-8 pb-12 max-w-6xl mx-auto">
        <div className="grid grid-cols-2 md:grid-cols-4 auto-rows-[150px] sm:auto-rows-[190px] gap-3 grid-flow-dense">
          {SPOTS.map((spot, i) => (
            <article
              key={spot.key}
              className={`group relative overflow-hidden rounded-xl bg-slate-100 ${SPANS[i % SPANS.length]} ${
                i === 0 ? "col-span-2 row-span-1" : "col-span-1 row-span-1"
              }`}
            >
              {spot.img ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={spot.img}
                  alt={zh ? spot.zh : spot.en}
                  loading={i < 4 ? "eager" : "lazy"}
                  className="absolute inset-0 w-full h-full object-cover transition duration-500 group-hover:scale-105"
                />
              ) : null}
              <div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/10 to-transparent" />
              <div className="absolute bottom-0 left-0 right-0 p-3.5 sm:p-4">
                <div className="text-white font-semibold text-[15px] sm:text-[18px] leading-tight drop-shadow">
                  {zh ? spot.zh : spot.en}
                </div>
                <div className="text-white/85 text-[11.5px] sm:text-[12.5px] mt-0.5 drop-shadow">
                  {zh ? spot.regionZh : spot.regionEn}
                </div>
              </div>
            </article>
          ))}
        </div>

        {/* Pexels attribution (required for hotlinked imagery) */}
        <div className="mt-5 text-[11.5px] text-slate-400">
          {tr.ex_attribution} ·{" "}
          {SPOTS.filter((s) => s.by)
            .slice(0, 6)
            .map((s, idx) => (
              <span key={s.key}>
                {idx > 0 ? ", " : ""}
                <a
                  href={s.creditUrl}
                  target="_blank"
                  rel="noreferrer noopener"
                  className="hover:text-slate-600 underline decoration-dotted"
                >
                  {s.by}
                </a>
              </span>
            ))}
        </div>
      </section>
    </div>
  );
}
