// AUTO-GENERATED by scripts/scrape-pexels.mjs — top NZ destinations + Pexels
// imagery. Re-run: PEXELS_KEY=<key> node scripts/scrape-pexels.mjs
// Imagery hotlinked from Pexels (free, attribution shown on /explore).

export interface Spot {
  key: string;
  en: string;
  zh: string;
  regionEn: string;
  regionZh: string;
  img: string;
  by: string;
  creditUrl: string;
}

export const SPOTS: Spot[] = [
  {
    "key": "milford",
    "en": "Milford Sound",
    "zh": "米尔福德峡湾",
    "regionEn": "Fiordland",
    "regionZh": "峡湾国家公园",
    "img": "https://images.pexels.com/photos/27623549/pexels-photo-27623549.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Donovan Kelly",
    "creditUrl": "https://www.pexels.com/photo/a-body-of-water-surrounded-by-mountains-27623549/"
  },
  {
    "key": "queenstown",
    "en": "Queenstown",
    "zh": "皇后镇",
    "regionEn": "Otago",
    "regionZh": "奥塔哥",
    "img": "https://images.pexels.com/photos/17824118/pexels-photo-17824118.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Donovan Kelly",
    "creditUrl": "https://www.pexels.com/photo/cloud-over-lake-and-town-in-mountains-17824118/"
  },
  {
    "key": "hobbiton",
    "en": "Hobbiton",
    "zh": "霍比特村",
    "regionEn": "Waikato",
    "regionZh": "怀卡托",
    "img": "https://images.pexels.com/photos/17824132/pexels-photo-17824132.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Donovan Kelly",
    "creditUrl": "https://www.pexels.com/photo/hill-in-the-hobbiton-movie-set-17824132/"
  },
  {
    "key": "rotorua",
    "en": "Rotorua",
    "zh": "罗托鲁瓦",
    "regionEn": "Bay of Plenty",
    "regionZh": "丰盛湾",
    "img": "https://images.pexels.com/photos/5926331/pexels-photo-5926331.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Richard Pan",
    "creditUrl": "https://www.pexels.com/photo/green-trees-near-the-lake-5926331/"
  },
  {
    "key": "tongariro",
    "en": "Tongariro",
    "zh": "汤加里罗",
    "regionEn": "Central Plateau",
    "regionZh": "中央高原",
    "img": "https://images.pexels.com/photos/4090328/pexels-photo-4090328.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Tomáš Malík",
    "creditUrl": "https://www.pexels.com/photo/rocky-terrain-with-green-lake-under-blue-sky-4090328/"
  },
  {
    "key": "aoraki",
    "en": "Aoraki / Mt Cook",
    "zh": "库克山",
    "regionEn": "Canterbury",
    "regionZh": "坎特伯雷",
    "img": "https://images.pexels.com/photos/34033017/pexels-photo-34033017.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Shashank Brahmavar",
    "creditUrl": "https://www.pexels.com/photo/majestic-snow-covered-mountain-peak-in-new-zealand-34033017/"
  },
  {
    "key": "bayofislands",
    "en": "Bay of Islands",
    "zh": "岛屿湾",
    "regionEn": "Northland",
    "regionZh": "北地",
    "img": "https://images.pexels.com/photos/25772418/pexels-photo-25772418.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Petra Reid",
    "creditUrl": "https://www.pexels.com/photo/hills-and-village-in-bay-on-sea-shore-25772418/"
  },
  {
    "key": "franzjosef",
    "en": "Franz Josef Glacier",
    "zh": "弗朗茨·约瑟夫冰川",
    "regionEn": "West Coast",
    "regionZh": "西海岸",
    "img": "https://images.pexels.com/photos/4471824/pexels-photo-4471824.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Tim O'Farrell",
    "creditUrl": "https://www.pexels.com/photo/a-placid-lake-scenery-across-the-mountains-4471824/"
  },
  {
    "key": "tekapo",
    "en": "Lake Tekapo",
    "zh": "特卡波湖",
    "regionEn": "Mackenzie",
    "regionZh": "麦肯齐",
    "img": "https://images.pexels.com/photos/7836395/pexels-photo-7836395.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Ken Cheung",
    "creditUrl": "https://www.pexels.com/photo/a-church-building-under-the-blue-starry-sky-at-night-7836395/"
  },
  {
    "key": "waitomo",
    "en": "Waitomo Caves",
    "zh": "怀托摩洞穴",
    "regionEn": "Waikato",
    "regionZh": "怀卡托",
    "img": "https://images.pexels.com/photos/4090094/pexels-photo-4090094.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "by": "Tomáš Malík",
    "creditUrl": "https://www.pexels.com/photo/glowing-worms-webs-in-dark-cave-4090094/"
  }
];
